name: sostat2021
channels:
  - conda-forge
  - defaults
dependencies:
  - astroml=0.4.1
  - astropy=5.0
  - astroquery=0.4.4
  - ipython=7.29.0
  - jupyterlab=3.2.4
  - matplotlib=3.5.0
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.3.1
  - python=3.8.12
  - pytorch=1.8.1
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - seaborn=0.11.2
  - stingray=0.3
  - torchvision=0.8.2
  - xeus-python==0.13.5
  - pip:
    - jupyterlab_latex
    - jupyterlab-link-share
