name: sostat2021
channels:
  - conda-forge
  - defaults
dependencies:
  - astroml=0.4.1
  - astropy=4.3.1
  - ipython=7.29.0
  - jupyterlab=3.2.3
  - matplotlib=3.4.3
  - numpy=1.21.4
  - pandas=1.3.4
  - python=3.9.7
  - scikit-learn=1.0.1
  - scipy=1.7.2
  - stingray=0.3
  - pip:
    - latex
